default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_filepath: ENV["HOME"] + "/ios/AuthKey.p8"
    )

    build_app(
      scheme: "Runner",
      export_method: "app-store"
    )

    upload_to_testflight
  end

  desc "Build and upload to App Store"
  lane :release do
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_filepath: ENV["HOME"] + "/ios/AuthKey.p8"
    )

    build_app(
      scheme: "Runner",
      export_method: "app-store"
    )

    upload_to_app_store(
      skip_screenshots: true,
      skip_metadata: true
    )
  end
end