default_platform(:ios)

platform :ios do
  def fetch_api_key
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_filepath: File.expand_path("~/ios/AuthKey.p8")
    )
  end

  desc "Build and upload to TestFlight"
  lane :beta do
    api_key = fetch_api_key

    build_app(
      scheme: "Runner",
      export_method: "app-store"
    )

    upload_to_testflight(api_key: api_key)
  end

  desc "Build and upload to App Store"
  lane :release do
    api_key = fetch_api_key

    build_app(
      scheme: "Runner",
      export_method: "app-store"
    )

    upload_to_app_store(
      api_key: api_key,
      skip_screenshots: true,
      skip_metadata: true
    )
  end
end