name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Build and Test Flutter App
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        architecture: 'x64'
        java-package: 'jdk'
        check-latest: false

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
        architecture: X64
        cache: false
        dry-run: false
        
    - name: Verify Flutter installation
      run: flutter --version

    - name: Install dependencies
      run: flutter pub get

    - name: Run tests
      run: flutter test
      continue-on-error: true

  # Publish to Google Play Store
  android_publish:
    runs-on: ubuntu-latest
    needs: build_and_test
    if: success()

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Java 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        architecture: 'x64'
        java-package: 'jdk'
        check-latest: false

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
        architecture: X64
        cache: false
        dry-run: false
        
    - name: Verify Flutter installation
      run: flutter --version

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK (Release)
      run: flutter build appbundle --release --no-tree-shake-icons
    
    - name: Authenticate with Google Play
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}

    - name: Upload to Google Play
      uses: r0adkll/sign-android-release@v1
      with:
        service_account_json: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
        package_name: com.askantechkode  # Replace with your app package name
        release_file: build/app/outputs/bundle/release/app-release.aab
        track: production  # Change to 'beta', 'production', etc., as required
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}

  # Publish to App Store (iOS)
  ios_publish:
    runs-on: macos-latest
    needs: build_and_test
    if: success()

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'

    - name: Install dependencies
      run: flutter pub get
            
    - name: Clean Flutter project
      run: flutter clean
      
    - name: Check Swift version
      run: swift --version

    - name: Build iOS (Release)
      run: flutter build ios --no-codesign  # Add --no-codesign flag to skip codesigning if needed

    - name: Set up fastlane
      run: |
        gem install fastlane
        fastlane --version

    - name: Fastlane match (Sign iOS app)
      run: |
        fastlane match appstore # For App Store distribution

      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}

    - name: Build and Upload to App Store
      run: |
        fastlane gym --scheme Runner --export_method app-store # Ensures signing during the build process
        fastlane deliver --ipa ./build/ios/ipa/Runner.ipa --skip_screenshots --skip_metadata --force
      env:
        APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
